### ISSUE TITLE
Is the molecular formula canonical ?

### ISSUE THREAD

**Issue by targos** [cheminfo/chemcalc-js#13]
https://en.wikipedia.org/wiki/Hill_system

**Comment by lpatiny** [comment]
Yes it is a canonical. We first put the C and H and then all the other atoms in alphabetical order. Actually I didn't know this was called the Hill system ;). I added a link on wikipedia. Wonder if it will stay ...

**Comment by lpatiny** [comment]
Funny I found this ticket back from google ;) Well the link in wikipedia is still there ...

Here is the code to sort an array of atom labels applying Hill system
```
    Object.keys(mfs).sort(function(a,b) {
        if (a==="C") return -1;
        if (a==="H" && b!=="C") return -1;
        if (a<b) return -1;
        return 1;
    });
```
