### ISSUE TITLE
Last version is very slow !

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/chemcalc-js#5]
When looking for molecular formula from a monoisotopic mass. For a specific example we obtain:

var start=Date.now();
CC.mfFromMonoisotopicMass(500,{mfRange: "C0-100H0-100O0-10N0-10Cl0-10Br0-10"})
console.log(Date.now()-start)

It is now 2 times slower.

In a more extreme case we had:

Now: 14417 ms
Before: 1824 ms

**Comment by targos** [comment]
Is the result exactly the same in both versions ?

**Comment by targos** [comment]
I checked, the result is different :  
Before : Object {options: Object, bruteForceIteration: 39522714, realIteration: 145919, numberResults: 3882, results: Array[1000]}
After : Object {options: Object, bruteForceIteration: 39522714, realIteration: 145919, numberResults: 3882, results: Array[3882]}

Note the size of the results array.

**Comment by lpatiny** [comment]
OK good. So it means the default value for the option does not work ?

maxNumberRows - Maximum number of results (rows) to retrieve (default: 1000)
