### ISSUE TITLE
convertAASequence crash if sequence is already converted

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/chemcalc-js#6]
Double conversion would crash chemcalc

**Comment by targos** [comment]
what are you trying to do ?
`CC.convertAASequence(CC.convertAASequence (sequence))`  ?

**Comment by targos** [comment]
if you know what to do to fix, the code is here : https://github.com/cheminfo/chemcalc-js/blob/master/src/org/chemcalc/js/client/Chemcalc.java#L44-L76

**Comment by lpatiny** [comment]
After investigation it appears that it was a problem in the view. There is no problems to convert many time the same sequence.
